--liquibase formatted sql

--changeset tinder4dogs:001-create-dog
--comment: the dog itself
CREATE TABLE dog (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(100) NOT NULL,
    breed  VARCHAR(100) NOT NULL,
    gender VARCHAR(10)  NOT NULL,
    age    INT          NOT NULL
);
--rollback DROP TABLE dog;

--changeset tinder4dogs:002-create-dog-preference
--comment: a dog's preferences, one row each
CREATE TABLE dog_preference (
    dog_id     BIGINT      NOT NULL,
    preference VARCHAR(50) NOT NULL,
    CONSTRAINT pk_dog_preference PRIMARY KEY (dog_id, preference),
    CONSTRAINT fk_dog_preference_dog FOREIGN KEY (dog_id)
        REFERENCES dog (id) ON DELETE CASCADE
);
--rollback DROP TABLE dog_preference;
